# Generated by Django 3.0.4 on 2020-04-06 13:18

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200406_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.get_upload_path_recipe),
        ),
    ]
