# Generated by Django 3.0.4 on 2020-04-02 09:29

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200402_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ingredients',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
